" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
set guioptions-=T  " no toolbar
 if has('gui_gtk3')
    set guifont=Overpass\ Mono\ 18
elseif has('gui_gnome')
    set guifont=Overpass\ Mono\ 18
elseif has('gui_gtk')
    set guifont=Overpass\ Mono\ 18
elseif has('gui_gtk2')
    set guifont=Overpass\ Mono\ 18
    "set guifont=Ubuntu\ Mono\ 12
    "set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
    "set guifont=Inconsolata\ 14
    "set guifont=DroidSansMono\ Nerd\ Font\ 12
    "set guifont=DejaVu\ Sans\ Mono\ 12
    "set guifont=Courier\ New\ 12 
 else
     set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
 endif

" Source a global configuration file if available
if filereadable("/etc/vim/gvimrc.local")
  source /etc/vim/gvimrc.local
endif

if filereadable("~/.vim/vimrc")
  source ~/.vim/vimrc
endif
