" Don't try to be vi compatible
set nocompatible "Configuração para instalar pacotes usando o bundle

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
" runtime! debian.vim
"let g:python_host_prog='/usr/bin/python2.7'
let g:python3_host_prog='/usr/bin/python3'

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
" set compatible

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
"
" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
    filetype plugin indent on
endif

syntax on

"Download automático do gerenciador de plugins
if ! filereadable(expand('~/.vim/autoload/plug.vim'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ~/.vim/autoload/
	silent !mkdir -p ~/.config/nvim/autoload/
	silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ~/.vim/autoload/plug.vim
    silent !cp ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/plug.vim
endif

filetype off

call plug#begin("~/.vim/bundle")
source ~/.vim/pluginsconfigs/pluginslist.vim
call plug#end()

source ~/.vim/pluginsconfigs/CommonConfigs.vim

"Para corrigir o bug que fica imprimindo bad characters na tela quando usamos o nvim no terminator adicione a linha
let g:UltiSnipsNoPythonWarning = 1
"https://github.com/neovim/neovim/issues/6041
set guicursor=

"Name of the word list file where words are added for the |zg| and |zw| commands.  It must end in ".{encoding}.add".  You need to include the path, otherwise the file is placed in the current directory.
set spellfile="~/.vim/spell/pt.utf-8.add"
set spellfile="~/.vim/spell/en.utf-8.add"

"This will use the directory "/home/supervedovatto/Documents/Programas/config/vim" and finally "$VIMRUNTIME" (the distributed runtime files).
"set runtimepath=$VIMRUNTIME,/home/supervedovatto/Documents/Programas/config/vim"
"set runtimepath=$VIMRUNTIME
"To see the current runtimepath type 
":set runtimepath?
